### PR TITLE
Fix search query and reveal

### PR DESCRIPTION
**Pull request by WorldSEnder**
Cute trick with the timeout and incremental reveal, it works really well in my tests ;)

### CODE REVIEW

**Comment by jplatte** [comment]
Can you provide any insights into why this fixes the search, and what's broken with the revealing of further search results that needs fixing?

**Comment by WorldSEnder** [comment]
- `InputEvent::data()` contains the *newly typed* data, and is empty when deleting content, which is the reason why it currently panics. Fixed by reading from the current value from the `input_ref`.
- The revealing is broken in that it doesn't limit the result to only `self.items_visible` items. Additionally, calculating if there are still items to reveal from the left-over scroll seemed more brittle than just testing against the actual length of `current_search_results`.

**Comment by jplatte** [comment]
I tested it, and actually your reveal change broke scrolling, I could only scroll down to some Rust 1.52 items, not further. I have picked up your changes that made the search work in the last commit of #59, thanks for that!

Feel free to post any follow-up PRs. In particular I noticed that the number of items isn't initially being limited when searching, only when there is no search query (maybe that's what you meant?).

**Comment by jplatte** [comment]
But for now, what I merged unblocked finally finishing the Yew 19 upgrade and decreased the wasm bundle size by about 50kb 🎉

**Pull request closed without merging**
