### PR TITLE
Add and fix flags

### PR DESCRIPTION
**Pull request by not-my-profile**

### CODE REVIEW

**Comment by jplatte** [comment]
The version of at least the `LinkedList::new` const feature was correct before. The attribute in the Rust standard library in incorrect. Here's the PR: https://github.com/rust-lang/rust/pull/63684 which was merged way after 1.32's release. Would be nice to include the PR number in the feature though (and of course fix the attribute upstream).

How did you find all of these by the way?

**Comment by not-my-profile** [comment]
Ah, nice catch! I updated the PR accordingly. I can take care of opening a PR upstream :)

I added the command I used to the commit message (please don't squash the commits^^).

**Comment by jplatte** [comment]
I've merged all of the commits except for the change of version for the `ManuallyDrop` features. Do you have a PR reference for that?

**Comment by not-my-profile** [comment]
Thank you! Right ... my bad. I thought that the `since` attributes in the source code were accurate. I just tested by installing Rust 1.31.0 and 1.32.0 with `rustup` and the `ManuallyDrop` functions indeed were stabilized in 1.32.0 ... I'll send a patch upstream.

**Pull request closed without merging**
